on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:
name: CI Build Flatpak
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:gnome-48
      options: --privileged
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
        with:
          bundle: atkAudio
          manifest-path: com.obsproject.Studio.Plugin.atkAudio.yaml
          cache-key: flatpak-builder-${{ github.sha }}
